name: Build Python Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright-browsers
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller playwright
          # Instala apenas o chromium para não inflar o tamanho do .exe
          playwright install chromium 

      - name: Build Executable with PyInstaller
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            SEP=";"
          else
            SEP=":"
          fi
          
          # Embutimos a pasta inteira diretamente, sem zipar
          pyinstaller --onefile --copy-metadata playwright --add-data "${PLAYWRIGHT_BROWSERS_PATH}${SEP}playwright-browsers" finnet.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/finnet*