name: Build Python Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      # Define o caminho absoluto para os navegadores (usando o diretório atual)
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright-browsers
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller playwright
          playwright install chromium
          # Verifica se a pasta foi criada (para depuração)
          ls -la $PLAYWRIGHT_BROWSERS_PATH || echo "Pasta não encontrada!"

      - name: Build Executable with PyInstaller
        run: |
          # Define o separador de acordo com o SO
          if [ "$RUNNER_OS" == "Windows" ]; then
            SEP=";"
          else
            SEP=":"
          fi
          # Caminho relativo ao diretório atual (onde o playwright-browsers foi criado)
          pyinstaller --onefile --copy-metadata playwright --add-data "playwright-browsers${SEP}playwright-browsers" finnet.py
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: dist/finnet*